name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
    # Set always-auth in npmrc
    # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
        node-version: '>=12'
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run-script build
    - name: Push to docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: rf31415/k8s-handson-front
        tags: 
          - latest
          - ${{ steps.vars.outputs.sha_short }}
